import { expect, test } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { gameReducer, initialState } from '../../../src/engine/gameReducer.js';
import { writeV2Save } from '../../../src/save/saveGame.ts';

test('a seeded Bard riddle rewards one answer and resumes without a second reward', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const started = gameReducer(initialState, { type: 'START_GAME', payload: { difficulty: 'easy', seed: 5 } });
  await page.addInitScript(raw => localStorage.setItem('lords-ledger-v2-save', raw), writeV2Save(started));
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.setViewportSize({ width: 1366, height: 768 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Load saved game' }).click();
  const tutorial = page.getByRole('button', { name: 'I Understand' });
  if (await tutorial.isVisible()) await tutorial.click();
  await page.getByRole('button', { name: /Map tab/ }).click();
  if (await tutorial.isVisible()) await tutorial.click();
  await page.locator('button[title="Enter the Boar\'s Head Tavern"]').click();
  await page.getByRole('button', { name: /The Bard's Corner/ }).click();
  await expect(page.getByText(/I have cities but no houses/)).toBeVisible();
  await expect(page.locator('.tavern-enter')).toHaveCount(0);
  await expect(page.locator('.quill-appear').last()).toHaveCSS('opacity', '1');
  await mkdir('artifacts/v2/bard-browser', { recursive: true });
  await page.screenshot({ path: 'artifacts/v2/bard-browser/riddle-1366x768.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/v2/bard-browser/riddle-390x844.png' });
  await page.getByRole('button', { name: 'Save game' }).click();
  const pendingRaw = await page.evaluate(() => localStorage.getItem('lords-ledger-v2-save'));
  if (!pendingRaw) throw new Error('Pending Bard riddle did not save.');
  const pending = JSON.parse(pendingRaw).state;
  const pendingPage = await page.context().newPage();
  pendingPage.on('pageerror', error => errors.push(error.message));
  await pendingPage.goto('/');
  await pendingPage.getByRole('button', { name: 'Load saved game' }).click();
  const pendingTutorial = pendingPage.getByRole('button', { name: 'I Understand' });
  if (await pendingTutorial.isVisible()) await pendingTutorial.click();
  await pendingPage.getByRole('button', { name: /Map tab/ }).click();
  if (await pendingTutorial.isVisible()) await pendingTutorial.click();
  await pendingPage.locator('button[title="Enter the Boar\'s Head Tavern"]').click();
  await expect(pendingPage.getByRole('button', { name: /The Bard's Corner/ })).toBeVisible();
  await expect(pendingPage.locator('.tavern-enter')).toHaveCount(0);
  await pendingPage.getByRole('button', { name: 'Save game' }).click();
  const beforeBardRaw = await pendingPage.evaluate(() => localStorage.getItem('lords-ledger-v2-save'));
  if (!beforeBardRaw) throw new Error('Pending Bard visit did not save.');
  const beforeBard = JSON.parse(beforeBardRaw).state;
  await pendingPage.getByRole('button', { name: /The Bard's Corner/ }).click();
  await expect(pendingPage.getByText(/I have cities but no houses/)).toBeVisible();
  await pendingPage.getByRole('button', { name: 'Save game' }).click();
  const resumedPendingRaw = await pendingPage.evaluate(() => localStorage.getItem('lords-ledger-v2-save'));
  if (!resumedPendingRaw) throw new Error('Resumed pending Bard riddle did not save.');
  const resumedPending = JSON.parse(resumedPendingRaw).state;
  expect(resumedPending.tavern.bardCurrentContent).toEqual(pending.tavern.bardCurrentContent);
  expect(resumedPending.rngState).toBe(beforeBard.rngState);
  await pendingPage.close();
  await page.getByRole('button', { name: 'A map', exact: true }).click();
  await expect(page.getByText('+10 denarii')).toBeVisible();
  await expect(page.locator('.quill-appear').last()).toHaveCSS('opacity', '1');
  const rewardBox = await page.getByText('+10 denarii').boundingBox();
  expect(rewardBox).not.toBeNull();
  if (rewardBox) expect(rewardBox.y + rewardBox.height).toBeLessThanOrEqual(844);
  await page.screenshot({ path: 'artifacts/v2/bard-browser/solved-390x844.png' });
  await page.getByRole('button', { name: 'Save game' }).click();
  const raw = await page.evaluate(() => localStorage.getItem('lords-ledger-v2-save'));
  if (!raw) throw new Error('Bard answer did not save.');
  const first = JSON.parse(raw).state;
  expect(first.denarii).toBe(710);
  expect(first.tavern.bardRiddlesSolved).toBe(1);
  expect(first.tavern.bardSolvedRiddleIds).toEqual(['map_without_houses']);
  expect(first.tavern.bardCurrentContent.answer).toBe('A map');

  const loadedPage = await page.context().newPage();
  loadedPage.on('pageerror', error => errors.push(error.message));
  await loadedPage.goto('/');
  await loadedPage.getByRole('button', { name: 'Load saved game' }).click();
  const loadedTutorial = loadedPage.getByRole('button', { name: 'I Understand' });
  if (await loadedTutorial.isVisible()) await loadedTutorial.click();
  await loadedPage.getByRole('button', { name: /Map tab/ }).click();
  if (await loadedTutorial.isVisible()) await loadedTutorial.click();
  await loadedPage.locator('button[title="Enter the Boar\'s Head Tavern"]').click();
  await loadedPage.getByRole('button', { name: /The Bard's Corner/ }).click();
  await expect(loadedPage.getByText('+10 denarii')).toHaveCount(0);
  await loadedPage.getByRole('button', { name: 'Save game' }).click();
  const continuedRaw = await loadedPage.evaluate(() => localStorage.getItem('lords-ledger-v2-save'));
  if (!continuedRaw) throw new Error('Continued Bard content did not save.');
  const continued = JSON.parse(continuedRaw).state;
  expect(continued.denarii).toBe(710);
  expect(continued.tavern.bardSolvedRiddleIds).toEqual(['map_without_houses']);
  expect(continued.tavern.bardCurrentContent).not.toEqual(first.tavern.bardCurrentContent);
  await loadedPage.close();

  for (let count = 0; count < 10; count++) {
    await page.getByRole('button', { name: 'Tell me more...' }).click();
  }
  await expect(page.getByText(/I have cities but no houses/)).toBeVisible();
  await page.getByRole('button', { name: 'A map', exact: true }).click();
  await expect(page.getByText('You know this one already. No new reward.')).toBeVisible();
  await page.getByRole('button', { name: 'Save game' }).click();
  const repeatedRaw = await page.evaluate(() => localStorage.getItem('lords-ledger-v2-save'));
  if (!repeatedRaw) throw new Error('Repeated Bard answer did not save.');
  const repeated = JSON.parse(repeatedRaw).state;
  expect(repeated.denarii).toBe(710);
  expect(repeated.tavern.bardRiddlesSolved).toBe(1);
  expect(repeated.tavern.bardCurrentContent.awarded).toBe(false);
  await page.getByRole('button', { name: 'Leave', exact: true }).click();
  await page.getByRole('button', { name: /The Bard's Corner/ }).click();
  await expect(page.locator('.tavern-enter')).toHaveCount(0);
  await expect(page.locator('.quill-appear').last()).toHaveCSS('opacity', '1');
  await page.screenshot({ path: 'artifacts/v2/bard-browser/reentered-390x844.png' });
  await page.getByRole('button', { name: 'Save game' }).click();
  const reenteredRaw = await page.evaluate(() => localStorage.getItem('lords-ledger-v2-save'));
  if (!reenteredRaw) throw new Error('Reentered Bard content did not save.');
  const reentered = JSON.parse(reenteredRaw).state;
  expect(reentered.rngState).not.toBe(repeated.rngState);
  expect(reentered.tavern.bardCurrentContent).not.toEqual(repeated.tavern.bardCurrentContent);
  expect(reentered.denarii).toBe(710);
  expect(errors).toEqual([]);
});
