import {present} from '../../gameInput.ts';
import { expect, test } from '@playwright/test';
import { createInitialState, gameReducer } from '../../../src/engine/gameReducer.ts';
import { writeV2Save } from '../../../src/save/saveGame.ts';
for(const width of [390,1366]) for(const legacy of [false,true]) test('missing Feast flag with current history shows already held at '+width+' effect-only '+legacy, async({page},info)=>{
  const base = { ...createInitialState(104), phase: 'management' as const, activeTab: 'hall', tutorialsSeen: ['hall'] };
  const completed = gameReducer(base,{type:'HALL_FEAST_COMPLETE',payload:{guestId:'village',entertainmentId:'musicians',courseId:'modest',seed:base.rngState}});
  const settled = {...completed, greatHall: {...completed.greatHall}};
  delete settled.greatHall.hasFeastedThisSeason;
  const first = present(present(settled.greatHall.feastHistory, 'history')[0], 'first feast');
  const history = legacy ? [Object.fromEntries(Object.entries(first).filter(([key]) => !['guestId','entertainmentId','courseId','eventId'].includes(key)))] : settled.greatHall.feastHistory;
  const fixture = {...settled, greatHall: {...settled.greatHall, feastHistory: history}};
  const raw = writeV2Save(fixture);
  await page.setViewportSize({width,height:844});
  await page.addInitScript(raw=>localStorage.setItem('lords-ledger-v2-save',raw),raw);
  await page.goto('/');await page.getByRole('button',{name:'Load saved game',exact:true}).click();
  await page.getByRole('button',{name:'Feast',exact:true}).click();
  await page.screenshot({path:info.outputPath('missing-flag.png'),fullPage:true});
  await expect(page.getByText('You have already held a feast this season.',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Save game',exact:true}).click();
  expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(raw);
});
