import {confirmForgeDialog} from '../forgeDialog.ts';
import {expect,test} from '@playwright/test';import {createInitialState,gameReducer} from '../../../src/engine/gameReducer.js';import {readV2Save,writeV2Save} from '../../../src/save/saveGame.ts';import seasonal from '../../../src/data/seasonalEvents.ts';import random from '../../../src/data/randomEvents.ts';
const payload={seasonalEvents:Object.values(seasonal).flat(),randomEvents:random};function snapshot(value:unknown){const r=readV2Save(writeV2Save(value));if(!r.ok)throw Error(r.error);return r.state;}
for(const width of [390,1366])for(const protect of [false,true])test(`Lock raid loss ${protect?'deployed':'stored'} ${width}`,async({page},info)=>{
 let expected=snapshot({...createInitialState(104),phase:'management',turn:16,year:4,season:'winter',activeTab:'estate',tutorialsSeen:['forge','estate'],inventoryCapacity:10000});expected={...expected,garrison:0,castleLevel:0,military:{...expected.military,walls:0,gate:0,moat:0,garrison:{levy:0,menAtArms:0,knights:0}}};for(const uid of [1,2,3])expected=snapshot(gameReducer(expected,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'lock_key',qualityScore:uid===3?0:50,completionUid:uid}}));expect(expected.blacksmith.inventory?.length).toBe(3);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:844});await page.addInitScript(raw=>{if(!localStorage.getItem('lords-ledger-v2-save'))localStorage.setItem('lords-ledger-v2-save',raw);},writeV2Save(expected));await page.goto('/');await page.getByRole('button',{name:'Load saved game',exact:true}).click();await page.getByRole('button',{name:'Forge tab',exact:true}).click();expected=snapshot(gameReducer(gameReducer(expected,{type:'SET_TAB',payload:{tab:'forge'}}),{type:'BLACKSMITH_VISIT'}));await expect(page.getByRole('heading',{name:'Godric',exact:true})).toBeVisible();await page.locator('button').filter({has:page.locator('span').filter({hasText:/^Armory$/})}).click();await page.getByRole('button',{name:'Select Scrap Lock & Key Set',exact:true}).click();await expect(page.getByRole('button',{name:'Deploy',exact:true})).toBeDisabled();await expect(page.getByRole('status').filter({hasText:'Provides no treasury protection.'})).toBeVisible();await page.screenshot({path:info.outputPath('broken.png'),animations:'disabled'});
 if(protect){await page.getByRole('button',{name:'Select Standard Lock & Key Set',exact:true}).first().focus();await page.keyboard.press('Enter');await page.keyboard.press('Tab');await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toContainText('Raid coin losses -5%, rounded up to whole denarii.');await page.screenshot({path:info.outputPath('confirmation.png'),animations:'disabled'});await confirmForgeDialog(page);expected=snapshot(gameReducer(expected,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));}
 await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));await page.reload();await page.getByRole('button',{name:'Load saved game',exact:true}).click();if(protect){await page.locator('button').filter({has:page.locator('span').filter({hasText:/^Armory$/})}).click();await page.getByRole('button',{name:'Select Standard Lock & Key Set',exact:true}).last().click();await page.getByRole('button',{name:'Deploy',exact:true}).click();await page.getByRole('button',{name:'Confirm',exact:true}).click();expected=snapshot(gameReducer(expected,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:2}}));}
 await page.getByRole('button',{name:/^Estate tab/}).click();expected=snapshot(gameReducer(expected,{type:'SET_TAB',payload:{tab:'estate'}}));await page.getByRole('button',{name:'Simulate this season',exact:true}).click();expected=snapshot(gameReducer(expected,{type:'SIMULATE_SEASON',payload}));expect(expected.phase).toBe('raid_warning');await expect(page.getByRole('button',{name:'Defend the Estate',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('warning.png'),animations:'disabled'});await page.getByRole('button',{name:'Defend the Estate',exact:true}).click();expected=snapshot(gameReducer(expected,{type:'RAID_DEFEND'}));if('scribesNote' in expected&&typeof expected.scribesNote==='string'&&expected.scribesNote){await page.getByRole('dialog',{name:"Scribe's Note",exact:true}).getByRole('button',{name:'Continue',exact:true}).click();expected=snapshot(gameReducer(expected,{type:'DISMISS_SCRIBES_NOTE'}));}
 const raid=page.locator('.raid-modal').filter({has:page.getByRole('heading',{name:'RAID SUCCESSFUL',exact:true})});await expect(raid.getByText(protect?'-114d stolen':'-119d stolen',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('raid-result.png'),animations:'disabled'});await raid.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));await page.reload();await page.getByRole('button',{name:'Load saved game',exact:true}).click();await expect(raid.getByText(protect?'-114d stolen':'-119d stolen',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('pending-reloaded.png'),animations:'disabled'});await raid.getByRole('button',{name:'Continue',exact:true}).click();expected=snapshot(gameReducer(expected,{type:'RAID_CONTINUE'}));await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));await page.reload();await page.getByRole('button',{name:'Load saved game',exact:true}).click();await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));expect(errors).toEqual([]);
});
