import {expect,test} from '@playwright/test';import {createInitialState,gameReducer} from '../../../src/engine/gameReducer.ts';import {GODRIC_MILITARY} from '../../../src/data/blacksmith.ts';import {writeV2Save,readV2Save} from '../../../src/save/saveGame.ts';
for(const width of [390,1366])for(const scenario of ['legacy','owned'])test('Forge functional equipment '+scenario+' '+width,async({page},info)=>{
 const loaded=readV2Save(writeV2Save({...createInitialState(104),phase:'management' as const,activeTab:'forge',tutorialsSeen:['forge']}));if(!loaded.ok)throw Error(loaded.error);let made=loaded.state;for(let uid=1;uid<=(scenario==='legacy'?5:2);uid++)made=gameReducer(made,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'dagger',qualityScore:scenario==='owned'&&uid===2?70:0,completionUid:uid}});
 const base=scenario==='legacy'?{...made,blacksmith:{...made.blacksmith,inventory:[],equipped:made.blacksmith.inventory??[]}}:{...made,blacksmith:{...made.blacksmith,inventory:(made.blacksmith.inventory??[]).map(item=>item.uid===2?{...item,name:'Older blade',grade:'Older quality',militaryBonus:1.5,qualityScore:0}:item)}};let expected=gameReducer(base,{type:'BLACKSMITH_VISIT'});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:844});await page.addInitScript(raw=>{if(!localStorage.getItem('lords-ledger-v2-save'))localStorage.setItem('lords-ledger-v2-save',raw);},writeV2Save(base));await page.goto('/');await page.getByRole('button',{name:'Load saved game',exact:true}).click();await expect(page.getByRole('heading',{name:'Godric',exact:true})).toBeVisible();
 async function nav(label:string){await page.locator('button').filter({has:page.locator('span').filter({hasText:new RegExp('^'+label+'$')})}).click();}
 if(scenario==='legacy'){await page.getByRole('button',{name:'Readiness',exact:true}).click();await page.screenshot({path:info.outputPath('advice.png'),animations:'disabled'});const lines=GODRIC_MILITARY.critical;await expect(page.getByText(lines[(base.blacksmith.totalItemsForged??0)%lines.length]??'',{exact:false})).toBeVisible();await nav('Armory');await expect(page.getByText('WEAPONS',{exact:true}).locator('..').getByText('0',{exact:true})).toBeVisible();await nav('Ledger');await expect(page.getByText('READINESS',{exact:true}).locator('..').getByText('0%',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('legacy-ledger.png'),animations:'disabled'});
 }else{await nav('Armory');await page.getByText('Dagger',{exact:true}).first().click();await page.screenshot({path:info.outputPath('selected.png'),animations:'disabled'});await expect(page.getByRole('button',{name:'Equip',exact:true})).toBeDisabled();const reason=page.getByRole('status').filter({hasText:'Provides no defense bonus.'});await expect(reason).toBeVisible();await reason.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('blocked.png'),animations:'disabled'});await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));await page.getByText('Older blade',{exact:true}).first().click();await page.getByRole('button',{name:'Equip',exact:true}).click();await page.getByRole('button',{name:'Confirm',exact:true}).click();expected=gameReducer(expected,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:2}});await expect(page.getByText('WEAPONS',{exact:true}).locator('..').getByText('1',{exact:true})).toBeVisible();}
 await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));await page.reload();await page.getByRole('button',{name:'Load saved game',exact:true}).click();await nav('Armory');await expect(page.getByText('WEAPONS',{exact:true}).locator('..').getByText(scenario==='legacy'?'0':'1',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));expect(errors).toEqual([]);
});
