import {expect,test} from '@playwright/test';
import {createInitialState,gameReducer} from '../../../src/engine/gameReducer.js';
import {writeV2Save,readV2Save} from '../../../src/save/saveGame.ts';
for(const width of [390,1366])for(const itemId of ['plowshare','scythe'])test(`Agriculture deployment ${itemId} ${width}`,async({page},info)=>{
 const loaded=readV2Save(writeV2Save({...createInitialState(104),phase:'management',turn:3,season:'autumn',activeTab:'forge',tutorialsSeen:['forge','estate'],inventoryCapacity:10000,buildings:[{type:'demesne_field',instanceId:'demesne-test',condition:100,builtOnTurn:0}]}));if(!loaded.ok)throw Error(loaded.error);
 let expected=gameReducer(loaded.state,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId,qualityScore:50,completionUid:1}});
 expected=gameReducer(expected,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId,qualityScore:0,completionUid:2}});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:844});await page.addInitScript(raw=>{if(!localStorage.getItem('lords-ledger-v2-save'))localStorage.setItem('lords-ledger-v2-save',raw);},writeV2Save(expected));
 await page.goto('/');await page.getByRole('button',{name:'Load saved game',exact:true}).click();await expect(page.getByRole('heading',{name:'Godric',exact:true})).toBeVisible();expected=gameReducer(expected,{type:'BLACKSMITH_VISIT'});
 async function nav(label:string){await page.locator('button').filter({has:page.locator('span').filter({hasText:new RegExp('^'+label+'$')})}).click();}
 await nav('Armory');const name=itemId==='plowshare'?'Plowshare':'Scythe';await page.getByText(name,{exact:true}).nth(1).click();await expect(page.getByRole('button',{name:'Deploy',exact:true})).toBeDisabled();await expect(page.getByRole('status').filter({hasText:'Broken tool.'})).toBeVisible();await page.getByRole('status').filter({hasText:'Broken tool.'}).scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('broken.png'),animations:'disabled'});
 const select=page.getByRole('button',{name:'Select Standard '+name,exact:true});await select.focus();await page.keyboard.press('Enter');await expect(select).toHaveAttribute('aria-expanded','true');await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Deploy',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Confirm',exact:true})).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Deploy',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Deploy on the Estate?',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('confirmation.png'),animations:'disabled'});await page.getByRole('button',{name:'Confirm',exact:true}).click();expected=gameReducer(expected,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}});
 await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));await page.reload();await page.getByRole('button',{name:'Load saved game',exact:true}).click();await nav('Armory');await expect(page.getByText('Equipped (1)',{exact:false})).toBeVisible();await page.getByText('Equipped (1)',{exact:false}).locator('..').getByText(name,{exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Deployed.'})).toBeVisible();await page.getByRole('status').filter({hasText:'Deployed.'}).scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('deployed.png'),animations:'disabled'});
 await page.getByRole('button',{name:'Estate tab',exact:true}).click();const output=page.getByText('Potential output:',{exact:true}).locator('..');await expect(output).toContainText(/16.*grain/);await expect(page.getByRole('button',{name:'I Understand',exact:true})).toHaveCount(0);await output.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.screenshot({path:info.outputPath('estate.png'),animations:'disabled'});expect(errors).toEqual([]);
});
