import {expect,test} from '@playwright/test';import {createInitialState,gameReducer} from '../../../src/engine/gameReducer.js';import {FORGE_SUPPLY_EVENTS,generateForgeMarketPrices} from '../../../src/data/blacksmith.ts';import {writeV2Save} from '../../../src/save/saveGame.ts';
for(const width of [390,1366])for(const event of FORGE_SUPPLY_EVENTS)test('Forge supply '+event.id+' settles once and quotes active prices '+width,async({page},info)=>{
 const initial=createInitialState(104),remaining=event.duration>0?Math.max(1,event.duration-1):0,base={...initial,phase:'management',turn:4,season:'winter',activeTab:'forge',tutorialsSeen:['forge'],blacksmith:{...initial.blacksmith,activeSupplyEvent:event,supplyEventTurnsLeft:remaining}},errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 let expected=gameReducer(base,{type:'BLACKSMITH_VISIT'});await page.setViewportSize({width,height:844});await page.addInitScript(raw=>{if(!localStorage.getItem('lords-ledger-v2-save'))localStorage.setItem('lords-ledger-v2-save',raw);},writeV2Save(base));await page.goto('/');await page.getByRole('button',{name:'Load saved game',exact:true}).click();await expect(page.getByRole('heading',{name:event.name,exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('pending.png'),animations:'disabled'});
 if(event.id==='iron_shortage'||event.id==='charcoal_surplus'){
  const resource=event.id==='iron_shortage'?'iron':'coal',price=generateForgeMarketPrices('winter',()=>0.5)[resource]*(event.id==='iron_shortage'?2:0.5);
  await page.locator('button').filter({has:page.locator('span').filter({hasText:/^Storefront$/})}).click();const row=page.getByTestId('forge-resource-'+resource);await expect(row).toContainText(`Price: ${price}d per`);await row.getByRole('button',{name:`Buy 1 (${price}d)`,exact:true}).click();expected=gameReducer(expected,{type:'BLACKSMITH_BUY_RESOURCE',payload:{resource,quantity:1}});
  await page.screenshot({path:info.outputPath('adjusted-market.png'),animations:'disabled'});
 }
 const type=event.effect==='iron_investment'?'BLACKSMITH_INVEST_IRON_VEIN':'BLACKSMITH_DISMISS_SUPPLY_EVENT';await page.getByRole('button',{name:event.effect==='iron_investment'?'Invest 30d':'Acknowledged',exact:true}).click();expected=gameReducer(expected,{type});
 if(event.duration>0){await expect(page.getByRole('button',{name:'Acknowledged',exact:true})).toHaveCount(0);await expect(page.getByRole('status').filter({hasText:/Supply conditions continue/})).toBeVisible();}else await expect(page.getByRole('heading',{name:event.name,exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));
 await page.reload();await page.getByRole('button',{name:'Load saved game',exact:true}).click();await expect(page.getByRole('button',{name:'Pump Bellows',exact:true})).toBeVisible();if(event.duration>0)await expect(page.getByRole('button',{name:'Acknowledged',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));await page.screenshot({path:info.outputPath('settled-reloaded.png'),animations:'disabled'});expect(errors).toEqual([]);
});
for(const width of [390,1366])test('Forge iron vein can be declined without cost '+width,async({page})=>{
 const initial=createInitialState(104),event=FORGE_SUPPLY_EVENTS.find(e=>e.id==='iron_vein');if(!event)throw Error('Missing vein');const base={...initial,phase:'management',turn:4,season:'winter',activeTab:'forge',tutorialsSeen:['forge'],blacksmith:{...initial.blacksmith,activeSupplyEvent:event}};
 await page.setViewportSize({width,height:844});await page.addInitScript(raw=>localStorage.setItem('lords-ledger-v2-save',raw),writeV2Save(base));await page.goto('/');await page.getByRole('button',{name:'Load saved game',exact:true}).click();await page.getByRole('button',{name:'Decline',exact:true}).click();await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(gameReducer(gameReducer(base,{type:'BLACKSMITH_VISIT'}),{type:'BLACKSMITH_DISMISS_SUPPLY_EVENT'})));
});
