import {expect,test} from '@playwright/test';
import {createInitialState,gameReducer} from '../../../src/engine/gameReducer.js';
import {readV2Save,writeV2Save} from '../../../src/save/saveGame.ts';
for(const width of [390,1366])for(const mode of ['build','upgrade'])test(`Nails construction quote ${mode} ${width}`,async({page},info)=>{
 const loaded=readV2Save(writeV2Save({...createInitialState(104),phase:'management',activeTab:'estate',tutorialsSeen:['forge','estate'],buildings:mode==='build'?[]:[{type:'strip_farm',instanceId:'start',condition:100,builtOnTurn:0}]}));if(!loaded.ok)throw Error(loaded.error);let expected=loaded.state;
 for(let uid=1;uid<=2;uid++)expected=gameReducer(expected,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'nails',qualityScore:uid===1?50:0,completionUid:uid}});
 expected={...expected,denarii:mode==='build'?76:114};const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:844});await page.addInitScript(raw=>{if(!localStorage.getItem('lords-ledger-v2-save'))localStorage.setItem('lords-ledger-v2-save',raw);},writeV2Save(expected));await page.goto('/');await page.getByRole('button',{name:'Load saved game',exact:true}).click();
 const area=mode==='build'?page.getByTestId('build-card-strip_farm'):page.getByTestId('built-building-start');const before=area.getByRole('button',{name:mode==='build'?'Need 80d (have 76d)':/Demesne Field \(120d\)/});await expect(before).toBeDisabled();await before.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.screenshot({path:info.outputPath('stored-quote.png'),animations:'disabled'});
 await page.getByRole('button',{name:'Forge tab',exact:true}).click();expected=gameReducer(gameReducer(expected,{type:'SET_TAB',payload:{tab:'forge'}}),{type:'BLACKSMITH_VISIT'});await expect(page.getByRole('heading',{name:'Godric',exact:true})).toBeVisible();await page.locator('button').filter({has:page.locator('span').filter({hasText:/^Armory$/})}).click();await page.getByRole('button',{name:'Select Scrap Nails (×100)',exact:true}).click();await expect(page.getByRole('button',{name:'Deploy',exact:true})).toBeDisabled();const broken=page.getByRole('status').filter({hasText:'Provides no construction discount.'});await expect(broken).toBeVisible();await broken.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.screenshot({path:info.outputPath('broken-nails.png'),animations:'disabled'});const select=page.getByRole('button',{name:'Select Standard Nails (×100)',exact:true});await select.focus();await page.keyboard.press('Enter');await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Deploy',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toContainText('Estate building and upgrade costs -5%, rounded up to whole denarii.');await page.screenshot({path:info.outputPath('deploy-quote.png'),animations:'disabled'});await page.keyboard.press('Enter');expected=gameReducer(expected,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}});
 await page.getByRole('button',{name:'Estate tab',exact:true}).click();expected=gameReducer(expected,{type:'SET_TAB',payload:{tab:'estate'}});const after=area.getByRole('button',{name:mode==='build'?'Build (76d)':/Demesne Field \(114d\)/});await expect(after).toBeEnabled();await after.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.screenshot({path:info.outputPath('deployed-quote.png'),animations:'disabled'});await after.click();expected=gameReducer(expected,{type:mode==='build'?'BUILD_BUILDING':'UPGRADE_BUILDING',payload:mode==='build'?{buildingId:'strip_farm'}:{buildingIndex:0}});await expect(page.getByTestId('resource-denarii')).toContainText('0');await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));await page.reload();await page.getByRole('button',{name:'Load saved game',exact:true}).click();await expect(page.getByTestId('resource-denarii')).toContainText('0');await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));expect(errors).toEqual([]);
});
