import {snapshotFixture} from '../../gameInput.ts';
import {present} from '../../gameInput.ts';
import {expect,test} from '@playwright/test';import {createInitialState,gameReducer} from '../../../src/engine/gameReducer.ts';import {writeV2Save} from '../../../src/save/saveGame.ts';
const envelope=(state:unknown)=>JSON.stringify({format:'lords-ledger',version:2,state});
for(const width of [390,1366])for(const scenario of ['uid','legacy','current','valid'])test('Forge save boundary '+scenario+' '+width,async({page},info)=>{
 const initial=createInitialState(104),owned=gameReducer({...initial,phase:'management' as const,activeTab:'forge',tutorialsSeen:['forge']},{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'dagger',qualityScore:70,completionUid:1}}),item={...present(owned.blacksmith.inventory, "owned.blacksmith.inventory")[0],name:'An older blade',grade:'Older quality',tradeValue:2.5,militaryBonus:1.5,cost:{wood:5,iron:3,gold:2},note:{old:true}},healthy={...owned,blacksmith:{...owned.blacksmith,inventory:[item],usedSupplyEventIds:['old_story','iron_shortage','iron_shortage']}},expected=gameReducer(snapshotFixture(healthy),{type:'BLACKSMITH_VISIT'}),broken={...healthy,blacksmith:{...healthy.blacksmith,...(scenario==='uid'?{nextItemUid:1}:scenario==='legacy'?{productionLog:[null]}:{marketPrices:{iron:1e-100}})}},bad=scenario==='legacy'?JSON.stringify(broken):envelope(broken),key=scenario==='legacy'?'lords-ledger-save':'lords-ledger-v2-save',errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:844});await page.addInitScript(({key,raw})=>{if(!localStorage.getItem(key))localStorage.setItem(key,raw);},{key,raw:scenario==='current'||scenario==='valid'?writeV2Save(healthy):bad});await page.goto('/');
 if(scenario==='current'||scenario==='valid'){await page.getByRole('button',{name:'Load saved game',exact:true}).click();await expect(page.getByRole('heading',{name:'Godric',exact:true})).toBeVisible();}
 if(scenario==='valid'){
  await page.locator('button').filter({has:page.locator('span').filter({hasText:/^Armory$/})}).click();await expect(page.getByText('An older blade',{exact:true})).toBeVisible();await expect(page.getByText('Older quality',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));await page.reload();await page.getByRole('button',{name:'Load saved game',exact:true}).click();await page.locator('button').filter({has:page.locator('span').filter({hasText:/^Armory$/})}).click();await expect(page.getByText('An older blade',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));
 }else{
  if(scenario==='current')await page.evaluate(raw=>localStorage.setItem('lords-ledger-v2-save',raw),bad);await page.getByRole('button',{name:scenario==='legacy'?'Import old save':'Load saved game',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Forge');expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe(bad);await page.screenshot({path:info.outputPath('rejected.png'),animations:'disabled'});
  if(scenario==='current'){await expect(page.getByRole('heading',{name:'Godric',exact:true})).toBeVisible();await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));}else {await expect(page.getByRole('heading',{name:"The Lord's Ledger",exact:true})).toBeVisible();if(scenario==='legacy')expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBeNull();}
 }
 await page.screenshot({path:info.outputPath(scenario+'.png'),animations:'disabled'});expect(errors).toEqual([]);
});

for(const width of [390,1366])test('Forge nullable arrays can Load then complete a real minigame '+width,async({page},info)=>{
 test.setTimeout(65000);const initial=createInitialState(104),base={...initial,phase:'management' as const,activeTab:'forge',tutorialsSeen:['forge'],blacksmith:{...initial.blacksmith,inventory:null,equipped:null,productionLog:null}},errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:844});await page.addInitScript(raw=>{if(!localStorage.getItem('lords-ledger-v2-save'))localStorage.setItem('lords-ledger-v2-save',raw);},writeV2Save(base));await page.goto('/');await page.getByRole('button',{name:'Load saved game',exact:true}).click();await page.locator('button').filter({has:page.locator('span').filter({hasText:/^Forging$/})}).click();await page.locator('button').filter({has:page.getByText('Dagger',{exact:true})}).click();await expect(page.getByRole('button',{name:'Collect Item',exact:true})).toBeVisible({timeout:35000});await page.getByRole('button',{name:'Collect Item',exact:true}).click();await expect(page.getByText('Quality: 0% | Broken',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('nullable-destination.png'),fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'Store in Armory',exact:true}).click();const expected=gameReducer(gameReducer(base,{type:'BLACKSMITH_VISIT'}),{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'dagger',qualityScore:0,completionUid:1}});await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));await page.reload();await page.getByRole('button',{name:'Load saved game',exact:true}).click();await page.locator('button').filter({has:page.locator('span').filter({hasText:/^Armory$/})}).click();await expect(page.getByText('Dagger',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));expect(errors).toEqual([]);
});
