import {confirmForgeDialog} from '../forgeDialog.ts';
import {expect,test} from '@playwright/test';import {createInitialState,gameReducer} from '../../../src/engine/gameReducer.ts';import {writeV2Save,readV2Save} from '../../../src/save/saveGame.ts';import seasonal from '../../../src/data/seasonalEvents.ts';import random from '../../../src/data/randomEvents.ts';
const payload={seasonalEvents:Object.values(seasonal).flat(),randomEvents:random};
function snapshot(value:unknown){const read=readV2Save(writeV2Save(value));if(!read.ok)throw Error(read.error);return read.state;}
for(const width of [390,1366])for(const condition of [100,51.8])test(`Fittings seasonal wear ${condition} ${width}`,async({page},info)=>{
 let expected=snapshot({...createInitialState(104),phase:'management' as const,activeTab:'estate',tutorialsSeen:['forge','estate'],denarii:1000,inventoryCapacity:10000,buildings:[{type:'strip_farm',instanceId:'wear',condition,builtOnTurn:0}]});for(let uid=1;uid<=2;uid++)expected=snapshot(gameReducer(expected,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'hinges_fittings',qualityScore:uid===1?50:0,completionUid:uid}}));
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:844});await page.addInitScript(raw=>{if(!localStorage.getItem('lords-ledger-v2-save'))localStorage.setItem('lords-ledger-v2-save',raw);},writeV2Save(expected));await page.goto('/');await page.getByRole('button',{name:'Load saved game',exact:true}).click();const card=page.getByTestId('built-building-wear');await expect(card).toContainText('After seasonal wear: '+(condition===100?'98':'49.8')+'%');
 await page.getByRole('button',{name:'Forge tab',exact:true}).click();expected=snapshot(gameReducer(gameReducer(expected,{type:'SET_TAB',payload:{tab:'forge'}}),{type:'BLACKSMITH_VISIT'}));await expect(page.getByRole('heading',{name:'Godric',exact:true})).toBeVisible();await page.locator('button').filter({has:page.locator('span').filter({hasText:/^Armory$/})}).click();await page.getByRole('button',{name:'Select Scrap Hinges & Fittings',exact:true}).click();await expect(page.getByRole('button',{name:'Deploy',exact:true})).toBeDisabled();await expect(page.getByRole('status').filter({hasText:'Provides no wear protection.'})).toBeVisible();const select=page.getByRole('button',{name:'Select Standard Hinges & Fittings',exact:true});await select.focus();await page.keyboard.press('Enter');await page.keyboard.press('Tab');await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toContainText('Seasonal building wear -5%.');await page.screenshot({path:info.outputPath('deploy.png'),animations:'disabled'});await confirmForgeDialog(page);expected=snapshot(gameReducer(expected,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));await page.getByRole('button',{name:/^Estate tab/}).click();expected=snapshot(gameReducer(expected,{type:'SET_TAB',payload:{tab:'estate'}}));await expect(card).toContainText('After seasonal wear: '+(condition===100?'98.1':'49.9')+'%');await card.getByText(/After seasonal wear:/).evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.screenshot({path:info.outputPath('forecast.png'),animations:'disabled'});
 await page.getByRole('button',{name:'Simulate this season',exact:true}).click();expected=snapshot(gameReducer(expected,{type:'SIMULATE_SEASON',payload}));await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));await page.reload();await page.getByRole('button',{name:'Load saved game',exact:true}).click();await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));
 for(let step=0;step<8&&expected.phase!=='management';step++){
  if('scribesNote' in expected&&typeof expected.scribesNote==='string'&&expected.scribesNote){await page.getByRole('dialog',{name:"Scribe's Note",exact:true}).getByRole('button',{name:'Continue',exact:true}).click();expected=snapshot(gameReducer(expected,{type:'DISMISS_SCRIBES_NOTE'}));continue;}
  if(expected.phase==='seasonal_action'){await page.getByRole('button',{name:/^Option 1:/}).click();expected=snapshot(gameReducer(expected,{type:'SELECT_SEASONAL_ACTION',payload:{optionIndex:0}}));}
  else if(expected.phase==='seasonal_resolve'){await page.getByRole('button',{name:'See What Happens Next',exact:true}).click();expected=snapshot(gameReducer(expected,{type:'CONTINUE_TO_RANDOM',payload}));}
  else if(expected.phase==='random_event'){await page.getByRole('button',{name:/^Option 1:/}).click();expected=snapshot(gameReducer(expected,{type:'SELECT_RANDOM_RESPONSE',payload:{optionIndex:0}}));}
  else if(expected.phase==='random_resolve'){await page.getByRole('button',{name:'Continue',exact:true}).click();expected=snapshot(gameReducer(expected,{type:'ADVANCE_TURN',payload}));}
  else throw Error('Unexpected phase '+expected.phase);
 }
 expect(expected.phase).toBe('management');await page.getByRole('button',{name:/^Estate tab/}).click();expected=snapshot(gameReducer(expected,{type:'SET_TAB',payload:{tab:'estate'}}));await expect(card).toContainText(condition===100?'Good (98.1%)':'Poor (49.9%)');await card.getByText('Condition:',{exact:true}).evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.screenshot({path:info.outputPath('after-season.png'),animations:'disabled'});await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));expect(errors).toEqual([]);
});
