import {expect,test} from '@playwright/test';
import {createInitialState,gameReducer} from '../../../src/engine/gameReducer.js';
import {readV2Save,writeV2Save} from '../../../src/save/saveGame.ts';
function snap(v:unknown){const r=readV2Save(writeV2Save(v));if(!r.ok)throw Error(r.error);return r.state;}
for(const width of [390,1366])for(const scenario of ['posted','pending','forge'])test(`Shared market supply ${scenario} ${width}`,async({page},info)=>{
 const initial=createInitialState(104);let expected=snap({...initial,phase:'management',activeTab:'market',denarii:10000,tutorialsSeen:['market','forge','estate']});
 if(scenario==='pending'){expected=snap(gameReducer(expected,{type:'HAGGLE_START',payload:{resource:'wool',quantity:5,merchantId:'agnes',mode:'buy'}}));expected=snap(gameReducer(expected,{type:'BUY_RESOURCE',payload:{resource:'wool',quantity:100,merchantId:'agnes'}}));}
 else expected=snap(gameReducer(expected,{type:'BUY_RESOURCE',payload:{resource:scenario==='forge'?'iron':'wool',quantity:99,...(scenario==='forge'?{}:{merchantId:'agnes'})}}));
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:844});await page.addInitScript(raw=>{if(!localStorage.getItem('lords-ledger-v2-save'))localStorage.setItem('lords-ledger-v2-save',raw);},writeV2Save(expected));await page.goto('/');await page.getByRole('button',{name:'Load saved game',exact:true}).click();
 if(scenario==='forge'){
 await page.getByRole('button',{name:'Forge tab',exact:true}).click();expected=snap(gameReducer(gameReducer(expected,{type:'SET_TAB',payload:{tab:'forge'}}),{type:'BLACKSMITH_VISIT'}));await page.locator('button').filter({has:page.locator('span').filter({hasText:/^Storefront$/})}).click();const row=page.getByTestId('forge-resource-iron');await expect(row).toContainText('Supply: 1');await row.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.screenshot({path:info.outputPath('forge-last-stock.png'),animations:'disabled'});await row.getByRole('button',{name:/^Buy 1 /}).focus();await page.keyboard.press('Enter');expected=snap(gameReducer(expected,{type:'BLACKSMITH_BUY_RESOURCE',payload:{resource:'iron',quantity:1}}));await expect(row.getByRole('button',{name:'Out of stock',exact:true})).toBeDisabled();await page.getByRole('button',{name:/^Market tab/}).click();expected=snap(gameReducer(expected,{type:'SET_TAB',payload:{tab:'market'}}));await page.getByRole('button',{name:/Quick Trade/}).click();const iron=page.getByTestId('quick-buy-iron');await expect(iron).toContainText('Supply: 0 this season');await expect(iron.getByRole('button',{name:/Buy 1/})).toBeDisabled();await iron.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.screenshot({path:info.outputPath('shared-quick-exhausted.png'),animations:'disabled'});
 }else if(scenario==='posted'){
 await page.getByRole('button',{name:/Agnes the Goodswoman/}).click();await page.getByRole('button',{name:'Buy from Merchant',exact:true}).click();const row=page.getByTestId('merchant-buy-wool');await expect(row).toContainText('Supply: 1 this season');await expect(row.getByRole('button',{name:/Buy 5/})).toBeDisabled();await row.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.screenshot({path:info.outputPath('posted-last-stock.png'),animations:'disabled'});await row.getByRole('button',{name:/Buy 1/}).focus();await page.keyboard.press('Enter');expected=snap(gameReducer(expected,{type:'BUY_RESOURCE',payload:{resource:'wool',quantity:1,merchantId:'agnes'}}));await expect(row).toContainText('Supply: 0 this season');await expect(row.getByRole('button',{name:/Buy 1/})).toBeDisabled();await expect(row.getByRole('button',{name:'Haggle',exact:true})).toHaveCount(0);await page.screenshot({path:info.outputPath('posted-exhausted.png'),animations:'disabled'});
 }else{
 await page.getByRole('button',{name:/Resume bargain/}).click();await expect(page.getByRole('button',{name:/^Accept /})).toBeDisabled();await expect(page.getByRole('status').filter({hasText:'Not enough denarii or seasonal supply'})).toBeVisible();await page.screenshot({path:info.outputPath('pending-exhausted.png'),animations:'disabled'});await page.getByRole('button',{name:'Walk Away',exact:true}).focus();await page.keyboard.press('Enter');expected=snap(gameReducer(expected,{type:'HAGGLE_WALK_AWAY'}));await expect(page.getByRole('button',{name:/^Accept /})).toHaveCount(0);
 }
 await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));await page.reload();await page.getByRole('button',{name:'Load saved game',exact:true}).click();await page.getByRole('button',{name:'Save game',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('lords-ledger-v2-save'))).toBe(writeV2Save(expected));expect(errors).toEqual([]);
});
