import { expect, test } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { gameReducer, initialState } from '../../../src/engine/gameReducer.js';
import { writeV2Save } from '../../../src/save/saveGame.ts';

test('a timed seeded cellar run settles once and survives save/load', async ({ page }) => {
  test.setTimeout(60_000); // The authored minigame runs for 20 real seconds after its countdown.
  await page.setViewportSize({ width: 1366, height: 768 });
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const started = gameReducer(initialState, { type: 'START_GAME', payload: { difficulty: 'easy', seed: 1 } });
  const saveKey = 'lords-ledger-v2-save';
  await page.addInitScript(({ key, raw }) => localStorage.setItem(key, raw),
    { key: saveKey, raw: writeV2Save(started) });
  await page.goto('/');
  await page.getByRole('button', { name: 'Load saved game' }).click();
  const tutorial = page.getByRole('button', { name: 'I Understand' });
  if (await tutorial.isVisible()) await tutorial.click();
  await page.getByRole('button', { name: /Map tab/ }).click();
  if (await tutorial.isVisible()) await tutorial.click();
  await page.locator('button[title="Enter the Boar\'s Head Tavern"]').click();
  await page.getByRole('button', { name: /Rats in the Cellar/ }).click();
  const note = page.getByRole('button', { name: 'Continue' });
  if (await note.isVisible()) await note.click();
  await mkdir('artifacts/v2/rats-browser', { recursive: true });
  await page.screenshot({ path: 'artifacts/v2/rats-browser/intro-1366x768.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/v2/rats-browser/intro-390x844.png' });
  await page.setViewportSize({ width: 1366, height: 768 });
  await page.getByRole('button', { name: 'Ready!' }).click();
  await page.getByRole('button', { name: /Rat in cell/ }).first().click({ timeout: 6_000 });
  await expect(page.getByText('Caught: 1')).toBeVisible();
  await page.getByRole('button', { name: /cell 1$/ }).focus();
  await page.keyboard.press('Tab');
  const focusedCell = page.getByRole('button', { name: /cell 2$/ });
  await expect(focusedCell).toBeFocused();
  await expect(focusedCell).toHaveCSS('outline-style', 'solid');
  await expect(page.getByRole('heading', { name: 'Cellar Cleared' })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByText('Escaped', { exact: true }).locator('..')).toContainText('15');
  await page.screenshot({ path: 'artifacts/v2/rats-browser/result-1366x768.png' });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.screenshot({ path: 'artifacts/v2/rats-browser/result-1280x720.png' });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.screenshot({ path: 'artifacts/v2/rats-browser/result-1920x1080.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/v2/rats-browser/result-390x844.png' });
  const collectBox = await page.getByRole('button', { name: 'Collect and Return' }).boundingBox();
  expect(collectBox).not.toBeNull();
  if (collectBox) expect(collectBox.y + collectBox.height).toBeLessThanOrEqual(844);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
  await page.getByRole('button', { name: 'Collect and Return' }).click();
  await page.getByRole('button', { name: 'Save game' }).click();
  const raw = await page.evaluate(key => localStorage.getItem(key), saveKey);
  if (!raw) throw new Error('The cellar run did not save.');
  const finished = JSON.parse(raw).state;
  expect(finished.denarii).toBe(700);
  expect(finished.tavern.ratsPlayedThisSeason).toBe(true);
  expect(finished.tavern.ratsBestScore).toBe(1);
  expect(finished.rngState).toBe(3087660854);
  const foodLost = 480 - finished.food;
  expect(foodLost).toBe(30);
  expect(finished.inventory.grain).toBe(350 - foodLost);

  const loadedPage = await page.context().newPage();
  loadedPage.on('pageerror', error => errors.push(error.message));
  loadedPage.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await loadedPage.goto('/');
  await loadedPage.getByRole('button', { name: 'Load saved game' }).click();
  const loadedTutorial = loadedPage.getByRole('button', { name: 'I Understand' });
  if (await loadedTutorial.isVisible()) await loadedTutorial.click();
  await loadedPage.getByRole('button', { name: /Map tab/ }).click();
  if (await loadedTutorial.isVisible()) await loadedTutorial.click();
  await loadedPage.locator('button[title="Enter the Boar\'s Head Tavern"]').click();
  await expect(loadedPage.getByRole('button', { name: /Rats in the Cellar/ })).toBeDisabled();
  expect(errors).toEqual([]);
});
