import assert from 'node:assert/strict';import test from 'node:test';
import {createInitialState,gameReducer} from '../../src/engine/gameReducer.js';
import {readV2Save,writeV2Save} from '../../src/save/saveGame.ts';
function loaded(value:unknown){const result=readV2Save(writeV2Save(value));if(!result.ok)throw Error(result.error);return result.state;}
function bells(faith=50){let state=loaded({...createInitialState(104),phase:'management',inventoryCapacity:10000});state={...state,chapel:{...state.chapel,faith}};for(const uid of [1,2,3])state=loaded(gameReducer(state,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'church_bell',qualityScore:uid===3?0:50,completionUid:uid}}));assert.equal(state.blacksmith.inventory?.length,3);return state;}
test('First working Church Bell grants8 Chapel faith exactly once, preserving records and RNG',()=>{const state=bells(),after=loaded(gameReducer(state,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));assert.equal(after.chapel.faith,58);assert.equal(after.rngState,state.rngState);assert.deepEqual(after.blacksmith.equipped?.[0],state.blacksmith.inventory?.[0]);assert.equal(gameReducer(after,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}),after);const duplicate=loaded(gameReducer(after,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:2}}));assert.equal(duplicate.chapel.faith,58);assert.equal(duplicate.blacksmith.equipped?.length,2);assert.equal(loaded(duplicate).chapel.faith,58);});
test('Bell faith caps100 and preserves zero; stored and broken bells have no gain',()=>{for(const faith of [0,95,100]){const state=bells(faith);assert.equal(state.chapel.faith,faith);assert.equal(gameReducer(state,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:3}}),state);assert.equal(loaded(gameReducer(state,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}})).chapel.faith,Math.min(100,faith+8));}});
test('Historical deployed bells retain saved faith on Load and prevent another installation gain',()=>{const state=bells(12),first=state.blacksmith.inventory?.[0];assert.ok(first);const old=loaded({...state,blacksmith:{...state.blacksmith,inventory:state.blacksmith.inventory?.slice(1),equipped:[first]}});assert.equal(old.chapel.faith,12);assert.equal(loaded(gameReducer(old,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:2}})).chapel.faith,12);});
test('Bad faith or invalid phase rejects Bell deployment atomically',()=>{const state=bells();for(const faith of [-1,101,NaN,Infinity,'50']){const malformed={...state,chapel:{...state.chapel,faith}};assert.equal(gameReducer(malformed,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}),malformed);}const wrong={...state,phase:'seasonal_action'};assert.equal(gameReducer(wrong,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}),wrong);});
