import assert from 'node:assert/strict';import test from 'node:test';import {createInitialState,gameReducer} from '../../src/engine/gameReducer.js';import {FORGEABLE_ITEMS,FORGE_SUPPLY_EVENTS} from '../../src/data/blacksmith.ts';import {readLegacySave,readV2Save,writeV2Save} from '../../src/save/saveGame.ts';import {seedLegacySnapshot} from '../../src/engine/random.ts';
const base=()=>({...createInitialState(104),phase:'management'});const raw=(state:unknown)=>JSON.stringify({format:'lords-ledger',version:2,state});
function reject(state:unknown){assert.throws(()=>writeV2Save(state),/Forge/);for(const result of [readV2Save(raw(state)),readLegacySave(JSON.stringify(state))]){assert.equal(result.ok,false);if(!result.ok){assert.match(result.error,/Forge/);assert.equal(result.canRestartManuscript,undefined);}}}
test('Every authored Forge completion remains exactly savable and legacy metadata is retained',()=>{
 for(const itemId of Object.keys(FORGEABLE_ITEMS))for(const qualityScore of [0,30,50,70,90]){const initial=base(),state={...initial,denarii:10000,inventory:{...initial.inventory,iron:1000,steel:1000,coal:1000,wood:1000,leather:1000}},next=gameReducer(state,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId,qualityScore,completionUid:1}});assert.notEqual(next,state);const read=readV2Save(writeV2Save(next));assert.ok(read.ok);assert.deepEqual(read.state,next);}
 const state=gameReducer(base(),{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'dagger',qualityScore:70,completionUid:1}}),item={...state.blacksmith.inventory[0],name:'An older blade',grade:'Older quality',militaryBonus:1.5,tradeValue:2.5,cost:{wood:5,iron:3,gold:2},note:{old:true}},old={...state,blacksmith:{...state.blacksmith,inventory:[item],usedSupplyEventIds:['old_story','iron_shortage','iron_shortage'],marketPrices:{iron:2.5,coal:null}}};const bytes=writeV2Save(old),read=readV2Save(bytes);assert.ok(read.ok);assert.deepEqual(read.state,old);assert.equal(writeV2Save(read.state),bytes);
});
test('Forge saves reject malformed owned identity, consumed fields, arrays and duplicate UIDs',()=>{
 const state=gameReducer(base(),{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'dagger',qualityScore:70,completionUid:1}}),item=state.blacksmith.inventory[0];for(const patch of [{uid:0},{uid:1.5},{itemId:'fake'},{category:'tool'},{name:7},{grade:[]},{qualityScore:-1},{qualityScore:101},{militaryBonus:'2'},{tradeValue:-1},{cost:{grain:1}},{cost:{iron:'2'}},{durability:4},{forgedTurn:2}])reject({...state,blacksmith:{...state.blacksmith,inventory:[{...item,...patch}]}});
 for(const patch of [{inventory:{}},{inventory:[null]},{equipped:'bad'},{inventory:[item,item]},{equipped:[item]},{nextItemUid:1},{nextItemUid:null},{productionLog:[null]},{productionLog:[{name:2,category:'weapon',grade:'Fine'}]},{priceHistory:[{turn:2,season:'summer',prices:{iron:2}}]}])reject({...state,blacksmith:{...state.blacksmith,...patch}});
 const sparse={...state,blacksmith:{...state.blacksmith,inventory:new Array(1)}};assert.throws(()=>writeV2Save(sparse),/Forge/);
});
test('Forge saves reject corrupted counters, prices, supply mechanics and receipts',()=>{
 const state=base();for(const patch of [{banterIndex:0.5},{watFactIndex:'0'},{godricRespect:101},{totalItemsForged:-1},{lastVisitTurn:2},{ironVeinActive:'false'},{soldToMortimer:1},{marketPrices:{iron:1e-100}},{marketPrices:{grain:2}},{marketPrices:{iron:'2'}},{supplyEventTurnsLeft:2},{activeSupplyEvent:{id:'fake'}},{activeSupplyEvent:{...FORGE_SUPPLY_EVENTS[0],effect:'royal_reward_50'}},{activeSupplyEvent:{...FORGE_SUPPLY_EVENTS[0],duration:999}},{usedSupplyEventIds:[null]},{priceHistory:[{turn:1,season:'winter',prices:{iron:2}}]}])reject({...state,blacksmith:{...state.blacksmith,...patch}});
 const sparse={...state,blacksmith:{...state.blacksmith,usedSupplyEventIds:new Array(1)}};assert.throws(()=>writeV2Save(sparse),/Forge/);
});
test('Forge nullish defaults, expired disruptions, pending instant rewards and old seed remain unchanged',()=>{
 const state=base();for(const key of Object.keys(state.blacksmith)){const old={...state,blacksmith:{...state.blacksmith,[key]:null}},read=readV2Save(writeV2Save(old));assert.ok(read.ok);assert.deepEqual(read.state,old);}
 for(const event of FORGE_SUPPLY_EVENTS)for(const remaining of [undefined,null,0,event.duration]){const old={...state,blacksmith:{...state.blacksmith,activeSupplyEvent:event,supplyEventTurnsLeft:remaining}},read=readV2Save(writeV2Save(old));assert.ok(read.ok);assert.deepEqual(read.state,JSON.parse(JSON.stringify(old)));}
 const {rngState,...legacy}=state;assert.ok(Number.isInteger(rngState));const result=readLegacySave(JSON.stringify(legacy));assert.ok(result.ok);assert.equal(result.state.rngState,seedLegacySnapshot(legacy));assert.deepEqual(result.state,{...legacy,rngState:seedLegacySnapshot(legacy)});
});

test('Accepted null Forge arrays support subsequent completion without normalizing the loaded save',()=>{
 for(const fields of [['inventory'],['equipped'],['productionLog'],['inventory','equipped','productionLog']]){const initial=base(),state={...initial,blacksmith:{...initial.blacksmith,...Object.fromEntries(fields.map(key=>[key,null]))}},bytes=writeV2Save(state),read=readV2Save(bytes);assert.ok(read.ok);assert.equal(writeV2Save(read.state),bytes);const next=gameReducer(read.state,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'dagger',qualityScore:70,completionUid:1}});assert.notEqual(next,read.state);assert.equal(next.blacksmith.inventory.length,1);assert.equal(next.blacksmith.productionLog.length,1);assert.equal(next.blacksmith.nextItemUid,2);assert.equal(next.rngState,state.rngState);assert.equal(writeV2Save(read.state),bytes);assert.ok(readV2Save(writeV2Save(next)).ok);}
});
