import assert from 'node:assert/strict';import test from 'node:test';import { createInitialState } from '../../src/engine/gameReducer.ts';
import { rawGameReducer as gameReducer } from '../gameInput.ts';import {getDeployableTool,getDeployedToolIds,getToolDescription} from '../../src/engine/forgeTools.ts';import {readV2Save,writeV2Save} from '../../src/save/saveGame.ts';
function snapshot(v:unknown){const r=readV2Save(writeV2Save(v));if(!r.ok)throw Error(r.error);return r.state;}
function vane(qualityScore=50,turn=3){const s=createInitialState(104);return snapshot(gameReducer({...s,phase:'management' as const,turn,season:['spring','summer','autumn','winter'][(turn-1)%4]},{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'weather_vane',qualityScore,completionUid:1}}));}
test('Weather Vane is a deployable working tool and its original item survives deployment/reload',()=>{const s=vane(),item=s.blacksmith.inventory?.[0];assert.ok(item);assert.ok(getDeployableTool('weather_vane'));const deployed=snapshot(gameReducer(s,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));assert.deepEqual(deployed.blacksmith.equipped?.[0],item);assert.ok([...getDeployedToolIds(deployed.blacksmith)].includes('weather_vane'));assert.equal(deployed.rngState,s.rngState);assert.ok(getToolDescription('weather_vane').includes('Next-season'));});
test('Broken Weather Vane rejects deployment rather than displaying a working outlook',()=>{const s=vane(0);assert.equal(gameReducer(s,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}),s);});
test('Stored vane is inert; historical working equipped vane qualifies without a new receipt',()=>{const s=vane(),item=s.blacksmith.inventory?.[0];assert.ok(item);assert.ok(![...getDeployedToolIds(s.blacksmith)].includes('weather_vane'));assert.ok([...getDeployedToolIds({equipped:[item,item]})].includes('weather_vane'));});
import {getWeatherVaneOutlook} from '../../src/engine/weatherVane.ts';
import {getBuildingOutput} from '../../src/engine/economyEngine.ts';
import {getAgricultureBonuses} from '../../src/engine/forgeAgriculture.ts';
import {getSeasonFoodRequirement} from '../../src/engine/foodRequirement.ts';
test('Autumn vane outlook uses actual winter50% output and150% wear with conditional current-state food needs',()=>{const s=vane(),deployed=snapshot(gameReducer({...s,population:5,garrison:5,buildings:[{instanceId:'farm',type:'strip_farm',condition:100,builtOnTurn:0}]},{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));assert.deepEqual(getWeatherVaneOutlook(deployed),{kind:'next',season:'winter' as const,turn:4,farmMultiplier:.5,wearMultiplier:1.5,farmFood:3,foodNeed:12});});
test('Outlook cycles seasons, respects current condition/agricultural bonuses, and excludes nonfarm producers',()=>{for(const [index,season] of ['spring','summer','autumn','winter'].entries()){const s=vane(50,index+1),next=['summer','autumn','winter','spring'][index];assert.ok(next==='spring'||next==='summer'||next==='autumn'||next==='winter');let deployed=snapshot(gameReducer({...s,turn:index+1,season,buildings:[{instanceId:'farm',type:'demesne_field',condition:49,builtOnTurn:0},{instanceId:'garden',type:'herb_garden',condition:100,builtOnTurn:0}]},{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));const extra=deployed.blacksmith.equipped?.[0];assert.ok(extra);deployed={...deployed,blacksmith:{...deployed.blacksmith,equipped:[extra,{...extra,uid:2,itemId:'plowshare'},{...extra,uid:3,itemId:'scythe'}]}};const result=getWeatherVaneOutlook(deployed);assert.ok(result?.kind==='next');assert.equal(result.season,next);const farm=deployed.buildings[0];assert.ok(farm);assert.equal(result.farmFood,getBuildingOutput(farm,deployed.buildings,next,getAgricultureBonuses(deployed.blacksmith)).grain);assert.equal(result.foodNeed,getSeasonFoodRequirement(deployed.population,deployed.garrison,next,deployed.difficulty).totalNeed);}});
test('Stored/broken vane is inert, duplicates do not alter outlook, preview is pure and final turn has no turn41',()=>{const stored=vane(),broken=vane(0),deployed=snapshot(gameReducer(stored,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));assert.equal(getWeatherVaneOutlook(stored),null);assert.equal(getWeatherVaneOutlook({...broken,blacksmith:{...broken.blacksmith,equipped:broken.blacksmith.inventory}}),null);const bytes=writeV2Save(deployed),result=getWeatherVaneOutlook(deployed);for(let i=0;i<10;i++)assert.deepEqual(getWeatherVaneOutlook(deployed),result);assert.equal(writeV2Save(deployed),bytes);assert.deepEqual(getWeatherVaneOutlook({...deployed,blacksmith:{...deployed.blacksmith,equipped:[...(deployed.blacksmith.equipped??[]),...(deployed.blacksmith.equipped??[])]}}),result);assert.deepEqual(getWeatherVaneOutlook({...deployed,turn:40,season:'winter' as const}),{kind:'final'});for(const turn of [0,41,.5,NaN])assert.equal(getWeatherVaneOutlook({...deployed,turn}),null);assert.equal(getWeatherVaneOutlook({...deployed,population:-1}),null);});
test('Readable extreme population cannot produce a nonfinite forecast; ordinary legacy fractions remain usable',()=>{const stored=vane(),deployed=snapshot(gameReducer(stored,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));const extreme=snapshot({...deployed,population:1e308});assert.equal(getWeatherVaneOutlook(extreme),null);const fraction=snapshot({...deployed,population:5.5});const result=getWeatherVaneOutlook(fraction);assert.ok(result?.kind==='next');assert.equal(result.foodNeed,14);});
