import assert from 'node:assert/strict';import test from 'node:test';import { createInitialState } from '../../src/engine/gameReducer.ts';
import { rawGameReducer as gameReducer } from '../gameInput.ts';import {resolveFeast,isFeastHistory} from '../../src/engine/feast.ts';import {readV2Save,writeV2Save,readLegacySave} from '../../src/save/saveGame.ts';
function snapshot(value:unknown){const r=readV2Save(writeV2Save(value));if(!r.ok)throw Error(r.error);return r.state;}
function pots(){let s=snapshot({...createInitialState(104),phase:'management' as const,inventoryCapacity:10000});for(const uid of [1,2,3])s=snapshot(gameReducer(s,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'cauldron',qualityScore:uid===3?0:50,completionUid:uid}}));assert.equal(s.blacksmith.inventory?.length,3);return s;}
const choice=(seed:number)=>({guestId:'village',entertainmentId:'musicians',courseId:'modest',seed});
test('Cauldron adds3 People approval exactly once and preserves event/draw/other effects',()=>{const stored=pots(),deployed=snapshot(gameReducer(stored,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}})),base=resolveFeast(choice(stored.rngState),stored.rngState,stored.blacksmith),boost=resolveFeast(choice(deployed.rngState),deployed.rngState,deployed.blacksmith);assert.ok(base&&boost);assert.equal(boost.totalEffects.people,base.totalEffects.people+3);assert.deepEqual({...boost.totalEffects,people:base.totalEffects.people},base.totalEffects);assert.equal(boost.event.id,base.event.id);assert.equal(boost.nextRandomState,base.nextRandomState);const duplicated=snapshot(gameReducer(deployed,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:2}}));assert.deepEqual(resolveFeast(choice(duplicated.rngState),duplicated.rngState,duplicated.blacksmith),boost);});
test('Bonus settlement survives Save/Load with exact history and cannot replay',()=>{const equipped=snapshot(gameReducer(pots(),{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}})),selection=choice(equipped.rngState),settled=snapshot(gameReducer(equipped,{type:'HALL_FEAST_COMPLETE',payload:{...selection,cauldronBonus:900,totalEffects:{people:900}}}));assert.equal(settled.greatHall.feastHistory?.[0]?.cauldronBonus,3);assert.ok(isFeastHistory(settled.greatHall.feastHistory));assert.equal(gameReducer(settled,{type:'HALL_FEAST_COMPLETE',payload:choice(settled.rngState)}),settled);assert.deepEqual(snapshot(settled).greatHall,settled.greatHall);});
test('Stored and broken pots grant no bonus; broken deployment rejects, meter caps remain',()=>{const state=pots();assert.equal(gameReducer(state,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:3}}),state);const broken=state.blacksmith.inventory?.[2];assert.ok(broken);const selection=choice(state.rngState);assert.deepEqual(resolveFeast(selection,state.rngState,{...state.blacksmith,equipped:[broken]}),resolveFeast(selection,state.rngState));const equipped=snapshot(gameReducer(state,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}})),nearCap={...equipped,greatHall:{...equipped.greatHall,meters:{...equipped.greatHall.meters,people:99}}};assert.equal(snapshot(gameReducer(nearCap,{type:'HALL_FEAST_COMPLETE',payload:choice(nearCap.rngState)})).greatHall.meters?.people,100);});
test('History rejects false/forged bonus metadata and preserves detailed/effect-only older saves',()=>{const state=pots(),old=snapshot(gameReducer(state,{type:'HALL_FEAST_COMPLETE',payload:choice(state.rngState)})),entry=old.greatHall.feastHistory?.[0];assert.ok(entry);assert.ok(isFeastHistory([entry]));for(const cauldronBonus of [0,1,2,4,900,-3,null,'3',false])assert.equal(isFeastHistory([{...entry,cauldronBonus}]),false);assert.equal(isFeastHistory([{...entry,cauldronBonus:3}]),false);const effectsOnly={season:entry.season,year:entry.year,totalEffects:entry.totalEffects};assert.ok(isFeastHistory([effectsOnly]));const legacy=readLegacySave(JSON.stringify({...old,greatHall:{...old.greatHall,feastHistory:[effectsOnly]}}));assert.ok(legacy.ok);if(legacy.ok)assert.deepEqual(legacy.state.greatHall.feastHistory,[effectsOnly]);});
test('Consumed Cauldron history rejects bad saves and missing or inconsistent receipts',()=>{const equipped=snapshot(gameReducer(pots(),{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}})),settled=snapshot(gameReducer(equipped,{type:'HALL_FEAST_COMPLETE',payload:choice(equipped.rngState)})),entry=settled.greatHall.feastHistory?.[0];assert.ok(entry);for(const cauldronBonus of [0,2,4,null,'3']){const bad:unknown={...settled,greatHall:{...settled.greatHall,feastHistory:[{...entry,cauldronBonus}]}};assert.throws(()=>writeV2Save(bad),/feast history/i);assert.equal(readV2Save(JSON.stringify({format:'lords-ledger',version:2,state:bad})).ok,false);}const missing={...entry};delete missing.cauldronBonus;assert.equal(isFeastHistory([missing]),false);assert.equal(isFeastHistory([{...entry,totalEffects:{...entry.totalEffects,people:entry.totalEffects.people+1}}]),false);Object.defineProperty(missing,'cauldronBonus',{value:3,enumerable:false});assert.equal(isFeastHistory([missing]),false);});
