import assert from 'node:assert/strict';import test from 'node:test';
import { createInitialState } from '../../src/engine/gameReducer.ts';
import { rawGameReducer as gameReducer } from '../gameInput.ts';import {resolveRaid} from '../../src/engine/raidEngine.ts';import {createRandomCursor} from '../../src/engine/random.ts';import {readV2Save,writeV2Save} from '../../src/save/saveGame.ts';
function record(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null&&!Array.isArray(value);}
function raidData(value:unknown){assert.ok(record(value)&&record(value.raids));const r=value.raids,a=r.activeRaid;return {delta:record(a)&&record(a.result)?a.result.denariiDelta:undefined,totalLost:r.totalDenariiLost};}
function snapshot(value:unknown){const r=readV2Save(writeV2Save(value));if(!r.ok)throw Error(r.error);return r.state;}
function locks(){let s=snapshot({...createInitialState(104),phase:'management' as const,inventoryCapacity:10000});for(const uid of [1,2,3])s=snapshot(gameReducer(s,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'lock_key',qualityScore:uid===3?0:50,completionUid:uid}}));assert.equal(s.blacksmith.inventory?.length,3);return s;}
function deployed(){return snapshot(gameReducer(locks(),{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}})).blacksmith;}
test('Lock protects rolled raid coin loss, includes castle penalty and uses whole denarii',()=>{const bs=deployed();assert.equal(resolveRaid('criminal',0,18,0,1,{},'normal',()=>.25,bs)?.denariiDelta,-48);assert.equal(resolveRaid('scottish',0,38,0,0,{},'normal',()=>.25,bs)?.denariiDelta,-129);});
test('Protection applies once without changing any other outcome or saved draw sequence',()=>{const bs=deployed(),item=bs.equipped?.[0];assert.ok(item);for(const type of ['criminal','scottish'] as const)for(const difficulty of ['easy','normal','hard'] as const)for(const defense of [0,1,10,17,18,37,38,80])for(const garrison of [0,5]){const a=createRandomCursor(104),b=createRandomCursor(104),old=resolveRaid(type,defense,type==='criminal'?18:38,garrison,0,{wool:12},difficulty,()=>a.next()),protectedResult=resolveRaid(type,defense,type==='criminal'?18:38,garrison,0,{wool:12},difficulty,()=>b.next(),{equipped:[item,{...item,uid:50}]});assert.ok(old&&protectedResult);assert.deepEqual(protectedResult,{...old,denariiDelta:old.denariiDelta<0?-Math.ceil(-old.denariiDelta*.95):old.denariiDelta});assert.equal(a.state,b.state);assert.equal(a.draws,b.draws);}});
test('Stored, broken and anonymous locks preserve old losses; broken deployment rejects',()=>{const state=locks(),bs=deployed(),item=bs.equipped?.[0];assert.ok(item);assert.equal(gameReducer(state,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:3}}),state);for(const equipped of [[],[{...item,qualityScore:0}],[{...item,grade:'Scrap'}],[{...item,uid:0}]])assert.equal(resolveRaid('criminal',0,18,0,1,{},'normal',()=>.25,{inventory:[item],equipped})?.denariiDelta,-50);});
test('Actual forced raid saves protected result and settles the same loss exactly once',()=>{const base=locks(),management=snapshot({...base,turn:16,year:4,season:'winter' as const,garrison:0,castleLevel:0,military:{...base.military,walls:0,gate:0,moat:0,garrison:{levy:0,menAtArms:0,knights:0}}});const equipped=snapshot(gameReducer(management,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}})),warning=snapshot(gameReducer(equipped,{type:'SIMULATE_SEASON'}));assert.equal(warning.phase,'raid_warning');const result=snapshot(gameReducer(warning,{type:'RAID_DEFEND'}));assert.equal(raidData(result).delta,-114);const restored=snapshot(result);assert.equal(restored.rngState,result.rngState);const next=snapshot(gameReducer(restored,{type:'RAID_CONTINUE'}));assert.equal(next.denarii,result.denarii-114);assert.equal(raidData(next).totalLost,114);assert.equal(gameReducer(next,{type:'RAID_CONTINUE'}),next);});
