import assert from 'node:assert/strict';import test from 'node:test';import {createInitialState,gameReducer} from '../../src/engine/gameReducer.js';import {marketQuickSalePrice} from '../../src/engine/marketHaggle.ts';import {readV2Save,writeV2Save} from '../../src/save/saveGame.ts';
function snapshot(value:unknown){const r=readV2Save(writeV2Save(value));if(!r.ok)throw Error(r.error);return r.state;}
function record(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null&&!Array.isArray(value);}
function prices(value:unknown){assert.ok(record(value)&&record(value.marketPrices));return value.marketPrices;}
function market(value:unknown){assert.ok(record(value)&&record(value.market));return value.market;}
function shoes(){const initial=createInitialState(104);let s=snapshot({...initial,phase:'management',inventoryCapacity:10000,inventory:{...initial.inventory,wool:30,cloth:30,honey:30,herbs:30,ale:30}});for(const uid of [1,2,3])s=snapshot(gameReducer(s,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'horseshoes',qualityScore:uid===3?0:50,completionUid:uid}}));assert.equal(s.blacksmith.inventory?.length,3);return s;}
function equipped(){return snapshot(gameReducer(shoes(),{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));}
test('Horseshoes boost all five posted trade-good sale totals5%, once, with exact owned costs and RNG',()=>{const state=equipped(),duplicate=snapshot(gameReducer(state,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:2}}));for(const resource of ['wool','cloth','honey','herbs','ale'] as const){const price=marketQuickSalePrice(prices(state),state.season,undefined,resource,[])??0;assert.ok(price>0);const after=snapshot(gameReducer(state,{type:'SELL_RESOURCE',payload:{resource,quantity:3,price:900}}));assert.equal(after.denarii,state.denarii+Math.round(price*105*3)/100);assert.equal(after.inventory[resource],state.inventory[resource]-3);assert.equal(after.rngState,state.rngState);assert.equal(snapshot(gameReducer(duplicate,{type:'SELL_RESOURCE',payload:{resource,quantity:3}})).denarii,after.denarii);}});
test('Existing saved haggle terms remain valid; actual paid income and ledger include bonus without changing reputation rules',()=>{const state=shoes(),pending=snapshot(gameReducer(state,{type:'HAGGLE_START',payload:{merchantId:'agnes',resource:'wool',quantity:3,mode:'sell'}})),terms=market(pending).activeHaggle;assert.ok(record(terms)&&typeof terms.currentOffer==='number');const plain=snapshot(gameReducer(pending,{type:'HAGGLE_ACCEPT'})),deployed=snapshot(gameReducer(pending,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));assert.deepEqual(market(deployed).activeHaggle,terms);const settled=snapshot(gameReducer(snapshot(deployed),{type:'HAGGLE_ACCEPT'})),income=Math.round(terms.currentOffer*105*3)/100;assert.equal(settled.denarii,deployed.denarii+income);assert.equal(market(settled).denariiEarnedFromTrade,income);assert.deepEqual(market(settled).reputation,market(plain).reputation);assert.equal(settled.rngState,plain.rngState);assert.equal(gameReducer(settled,{type:'HAGGLE_ACCEPT'}),settled);});
test('Broken Horseshoes deployment rejects and inventory grants no sale boost',()=>{const state=shoes();assert.equal(gameReducer(state,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:3}}),state);const price=marketQuickSalePrice(prices(state),state.season,undefined,'wool',[])??0;assert.equal(snapshot(gameReducer(state,{type:'SELL_RESOURCE',payload:{resource:'wool',quantity:3}})).denarii,state.denarii+price*3);});
test('Food/raw material sales and purchases keep their previous amounts with Horseshoes',()=>{const state=equipped();for(const resource of ['grain','iron'] as const){const price=marketQuickSalePrice(prices(state),state.season,undefined,resource,[])??0;assert.equal(snapshot(gameReducer(state,{type:'SELL_RESOURCE',payload:{resource,quantity:1}})).denarii,state.denarii+price);}const without={...state,blacksmith:{...state.blacksmith,equipped:[]}};assert.equal(snapshot(gameReducer(state,{type:'BUY_RESOURCE',payload:{resource:'grain',quantity:1}})).denarii,snapshot(gameReducer(without,{type:'BUY_RESOURCE',payload:{resource:'grain',quantity:1}})).denarii);});
import {marketSaleProceeds,hasHorseshoeTradeBonus} from '../../src/engine/marketHaggle.ts';
test('Shared proceeds settle clean cents and preserve old fractional arithmetic without eligible shoes',()=>{const state=equipped(),item=state.blacksmith.equipped?.[0];assert.ok(item);assert.equal(marketSaleProceeds(2,3,'wool',state.blacksmith),6.3);assert.equal(marketSaleProceeds(3,.5,'wool',state.blacksmith),1.58);for(const equipped of [[],[{...item,uid:0}],[{...item,grade:'Scrap'}],[{...item,qualityScore:29}]]){assert.equal(hasHorseshoeTradeBonus('wool',{equipped}),false);assert.equal(marketSaleProceeds(2.123,3,'wool',{equipped}),2.123*3);}assert.equal(hasHorseshoeTradeBonus('grain',state.blacksmith),false);});
test('Rounded bonus never reduces accepted legacy fractional trade proceeds',()=>{const state=equipped();for(const income of [.001,.009,.052,.101,1.5,13.123]){assert.ok(marketSaleProceeds(1,income,'wool',state.blacksmith)>=income);}const price=marketQuickSalePrice(prices(state),state.season,undefined,'wool',[])??0,quantity=.052/price,legacy=snapshot({...state,inventory:{...state.inventory,wool:quantity}}),sold=snapshot(gameReducer(legacy,{type:'SELL_RESOURCE',payload:{resource:'wool',quantity:1}}));assert.ok(sold.denarii>=legacy.denarii+quantity*price);});
