import assert from 'node:assert/strict';import test from 'node:test';import { createInitialState } from '../../src/engine/gameReducer.ts';
import { rawGameReducer as gameReducer } from '../gameInput.ts';import {getDeployableTool,getDeployedToolIds} from '../../src/engine/forgeTools.ts';import {computeReputation} from '../../src/data/greatHall.ts';import {readV2Save,writeV2Save} from '../../src/save/saveGame.ts';
function snapshot(v:unknown){const r=readV2Save(writeV2Save(v));if(!r.ok)throw Error(r.error);return r.state;}
function chandeliers(withRuling=true){const initial=createInitialState(104);let s=snapshot({...initial,phase:'management' as const});if(withRuling)s=snapshot(gameReducer(s,{type:'HALL_RULE_DISPUTE',payload:{disputeId:'dispute_001',rulingId:'a'}}));for(const uid of [1,2,3])s=snapshot(gameReducer(s,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'chandelier',qualityScore:uid===3?0:50,completionUid:uid}}));return s;}
test('Chandelier prestige advances earned title thresholds without modifying path scores/history or RNG',()=>{const s=chandeliers(),item=s.blacksmith.inventory?.[0];assert.ok(item);assert.ok(getDeployableTool('chandelier'));assert.equal(s.greatHall.reputation,'Gentle Hand');const deployed=snapshot(gameReducer(s,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));assert.equal(deployed.greatHall.reputation,'The Merciful');assert.equal(deployed.greatHall.reputationTrack,'merciful');assert.deepEqual(deployed.greatHall.reputationScores,s.greatHall.reputationScores);assert.deepEqual(deployed.greatHall.rulingHistory,s.greatHall.rulingHistory);assert.equal(deployed.rngState,s.rngState);assert.deepEqual(deployed.blacksmith.equipped?.[0],item);assert.equal(gameReducer(deployed,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}),deployed);});
test('Broken Chandelier deployment rejects and stored lamps grant no prestige',()=>{const s=chandeliers();assert.equal(gameReducer(s,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:3}}),s);assert.ok(![...getDeployedToolIds(s.blacksmith)].includes('chandelier'));});
test('Prestige changes only reputation titles; no history retains Unknown Lord and no moral track',()=>{const history=[{consequences:{people:5,treasury:-2,church:0,military:0}}];const old=computeReputation(history),boosted=computeReputation(history,3);assert.equal(boosted.title,'The Merciful');assert.equal(boosted.track,old.track);assert.deepEqual(boosted.scores,old.scores);assert.deepEqual(computeReputation([],3),{track:null,title:'Unknown Lord',scores:{}});});
test('First lamp with no rulings invents no track; duplicate lamps and season changes do not stack prestige',()=>{const unknown=chandeliers(false),first=snapshot(gameReducer(unknown,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));assert.equal(first.greatHall.reputation,'Unknown Lord');assert.equal(first.greatHall.reputationTrack,null);const s=chandeliers(),one=snapshot(gameReducer(s,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}})),two=snapshot(gameReducer(one,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:2}}));assert.equal(two.greatHall.reputation,'The Merciful');const next=snapshot(gameReducer({...two,phase:'random_resolve' as const},{type:'ADVANCE_TURN'}));assert.equal(next.greatHall.reputation,'The Merciful');assert.deepEqual(next.greatHall.reputationScores,s.greatHall.reputationScores);});
import {getChandelierPrestigeBonus} from '../../src/engine/forgeTools.ts';import {exportPitchData} from '../../src/data/greatHall.ts';
test('Legacy cached scores remain byte-for-byte through first deployment and established equipment Load is not normalized',()=>{const s=chandeliers(),legacy=snapshot({...s,greatHall:{...s.greatHall,reputationScores:{merciful:5.25,balanced:2.5}}}),one=snapshot(gameReducer(legacy,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));assert.deepEqual(one.greatHall.reputationScores,legacy.greatHall.reputationScores);const old=snapshot({...one,greatHall:{...one.greatHall,reputation:'Gentle Hand'}}),loaded=gameReducer(old,{type:'LOAD_SAVE',payload:{savedState:old}});assert.equal(writeV2Save(loaded),writeV2Save(old));assert.equal(getChandelierPrestigeBonus(old.blacksmith),3);assert.equal(computeReputation(old.greatHall.rulingHistory,getChandelierPrestigeBonus(old.blacksmith)).title,'The Merciful');assert.equal(exportPitchData(old,getChandelierPrestigeBonus(old.blacksmith)).reputation,'The Merciful');const noHistory=snapshot({...s,greatHall:{...s.greatHall,rulingHistory:null,reputation:'Old Lord',reputationTrack:null,reputationScores:{}}});const deployed=snapshot(gameReducer(noHistory,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}));assert.deepEqual(deployed.greatHall,noHistory.greatHall);});
test('Known working ownership and finite quality guard prestige; damaged consumed Hall history cannot deploy a first lamp',()=>{const s=chandeliers(),item=s.blacksmith.inventory?.[0];assert.ok(item);for(const equipped of [[],[{...item,uid:0}],[{...item,grade:'Scrap'}],[{...item,qualityScore:29}],[{...item,qualityScore:101}],[{...item,category:'weapon'}]])assert.equal(getChandelierPrestigeBonus({equipped}),0);assert.equal(getChandelierPrestigeBonus({equipped:[{...item,qualityScore:null},item]}),3);const bad={...s,greatHall:{...s.greatHall,rulingHistory:'bad'}};assert.equal(gameReducer(bad,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}}),bad);});
