import type {GameSnapshot} from '../../src/save/saveGame.ts';
import {present} from '../gameInput.ts';
import assert from 'node:assert/strict';import test from 'node:test';import { createInitialState } from '../../src/engine/gameReducer.ts';
import { rawGameReducer as gameReducer } from '../gameInput.ts';import {calculateForgeReadiness} from '../../src/engine/forgeReadiness.ts';import {deriveGodricMood,getGodricRecommendation,getReadinessTier} from '../../src/data/blacksmith.ts';import {writeV2Save,readV2Save} from '../../src/save/saveGame.ts';
function forged(itemId='dagger',qualityScore=0){return gameReducer({...createInitialState(104),phase:'management' as const},{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId,qualityScore,completionUid:1}});}
test('Old canonical broken equipment retains exact save metadata but grants no functional arming',()=>{
 let state: GameSnapshot={...createInitialState(104),phase:'management' as const};for(let uid=1;uid<=5;uid++)state=gameReducer(state,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'dagger',qualityScore:0,completionUid:uid}});const legacy={...state,blacksmith:{...state.blacksmith,inventory:[],equipped:state.blacksmith.inventory}},bytes=writeV2Save(legacy),read=readV2Save(bytes);assert.ok(read.ok);assert.deepEqual(calculateForgeReadiness(present(legacy.blacksmith.equipped, "legacy.blacksmith.equipped"),5),{readiness:0,armed:0,armored:0,quality:0,defenseBonus:0});assert.equal(getReadinessTier(present(legacy.blacksmith.equipped, "legacy.blacksmith.equipped"),5),'critical');assert.equal(writeV2Save(read.state),bytes);assert.equal(deriveGodricMood(legacy),'worried');assert.match(getGodricRecommendation({...legacy,garrison:6}),/needs swords/);
});
test('Zero-bonus military equip rejects without consuming an item; positive historical stats remain usable',()=>{
 for(const itemId of ['dagger','leather_jerkin']){const state=forged(itemId);assert.equal(present(state.blacksmith.inventory, "state.blacksmith.inventory").length,1);const next=gameReducer(state,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}});assert.equal(next,state);assert.equal(next.rngState,state.rngState);}
 const state=forged(),item={...present(state.blacksmith.inventory, "state.blacksmith.inventory")[0],name:'Older blade',militaryBonus:1.5},old={...state,blacksmith:{...state.blacksmith,inventory:[item]}},next=gameReducer(old,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}});assert.equal(present(next.blacksmith.equipped, "next.blacksmith.equipped")[0],item);assert.deepEqual(calculateForgeReadiness(present(next.blacksmith.equipped, "next.blacksmith.equipped"),5),{readiness:8,armed:1,armored:0,quality:0,defenseBonus:1});assert.equal(next.rngState,old.rngState);
});
test('Mixed equipment counts only positive-bonus arms and retains the existing flat-defense sum',()=>{
 const items=[{category:'weapon',militaryBonus:1,qualityScore:70},{category:'weapon',militaryBonus:0,qualityScore:0},{category:'armor',militaryBonus:null,qualityScore:50},{category:'armor',militaryBonus:2,qualityScore:70},{category:'tool',militaryBonus:3,qualityScore:100}];assert.deepEqual(calculateForgeReadiness(items,5),{readiness:38,armed:1,armored:1,quality:80,defenseBonus:3});
});
