import assert from 'node:assert/strict';import test from 'node:test';
import {buildToolEstate,replayToolEstate,checkedSnapshot,TOOL_IDS} from '../fixtures/forgeTools.ts';

import { rawGameReducer as gameReducer } from '../gameInput.ts';
import {getDeployedToolIds,getChandelierPrestigeBonus,getConstructionCost} from '../../src/engine/forgeTools.ts';
import {getAgricultureBonuses} from '../../src/engine/forgeAgriculture.ts';
import {getBuildingOutput} from '../../src/engine/economyEngine.ts';
import {getWeatherVaneOutlook} from '../../src/engine/weatherVane.ts';
import {resolveRaid} from '../../src/engine/raidEngine.ts';
import {resolveFeast,getCauldronFeastBonus,type FeastSelection} from '../../src/engine/feast.ts';
import {writeV2Save} from '../../src/save/saveGame.ts';
import seasonal from '../../src/data/seasonalEvents.ts';import random from '../../src/data/randomEvents.ts';
for(const seed of [1,104,600])test('All ten tools coexist through paid startup commands, exact replay, trade, feast and season '+seed,()=>{
 const {state,actions}=buildToolEstate(seed);assert.equal(getDeployedToolIds(state.blacksmith).size,10);assert.deepEqual([...getDeployedToolIds(state.blacksmith)],TOOL_IDS);assert.equal(state.blacksmith.inventory?.length,0);assert.equal(state.chapel.faith,58);assert.equal(state.greatHall.reputation,'The Merciful');assert.equal(state.greatHall.reputationScores?.merciful,5);assert.equal(getConstructionCost(200,state.blacksmith),190);assert.equal(getCauldronFeastBonus(state.blacksmith),3);assert.equal(getChandelierPrestigeBonus(state.blacksmith),3);assert.deepEqual(getAgricultureBonuses(state.blacksmith),{food:.05,harvest:.05});assert.equal(writeV2Save(replayToolEstate(seed,actions)),writeV2Save(state));
 const farm=state.buildings.find(b=>typeof b!=='string'&&b.type==='demesne_field');assert.ok(farm&&typeof farm!=='string');assert.equal(getBuildingOutput(farm,state.buildings,'spring',getAgricultureBonuses(state.blacksmith)).grain,7);const forecast=getWeatherVaneOutlook(state);assert.ok(forecast?.kind==='next');assert.equal(forecast.season,'summer');assert.equal(forecast.farmFood,11);const before=writeV2Save(state);getWeatherVaneOutlook(state);assert.equal(writeV2Save(state),before);
 const raided=resolveRaid('criminal',0,18,0,1,state.inventory,'normal',()=>.25,state.blacksmith);assert.equal(raided?.denariiDelta,-48);
 const bought=checkedSnapshot(gameReducer(state,{type:'BUY_RESOURCE',payload:{resource:'wool',quantity:1,merchantId:'agnes'}}));assert.equal(bought.inventory.wool,1);const sold=checkedSnapshot(gameReducer(bought,{type:'SELL_RESOURCE',payload:{resource:'wool',quantity:1,merchantId:'agnes'}}));const prices:unknown=bought;assert.ok(typeof prices==='object'&&prices!==null&&'marketPrices' in prices);const market=prices.marketPrices;assert.ok(typeof market==='object'&&market!==null&&'sell' in market);const quote=market.sell;assert.ok(typeof quote==='object'&&quote!==null&&'wool' in quote&&typeof quote.wool==='number');assert.equal(sold.denarii,bought.denarii+quote.wool+Math.round(quote.wool*5)/100);assert.equal(sold.inventory.wool,0);assert.equal(sold.rngState,bought.rngState);
 const selection:FeastSelection={guestId:'village',entertainmentId:'musicians',courseId:'modest',seed:sold.rngState},plain=resolveFeast(selection,sold.rngState),boosted=resolveFeast(selection,sold.rngState,sold.blacksmith);assert.ok(plain&&boosted);assert.equal(boosted.totalEffects.people,plain.totalEffects.people+3);assert.equal(boosted.nextRandomState,plain.nextRandomState);const feasted=checkedSnapshot(gameReducer(sold,{type:'HALL_FEAST_COMPLETE',payload:selection}));assert.equal(feasted.rngState,boosted.nextRandomState);assert.equal(feasted.greatHall.feastHistory?.[0]?.cauldronBonus,3);assert.equal(feasted.greatHall.reputationScores?.merciful,5);
 const resolved=checkedSnapshot(gameReducer(feasted,{type:'SIMULATE_SEASON',payload:{seasonalEvents:Object.values(seasonal).flat(),randomEvents:random}}));const worn=resolved.buildings.find(b=>typeof b!=='string'&&b.type==='demesne_field');assert.ok(worn&&typeof worn!=='string');assert.equal(worn.condition,98.1);assert.equal(resolved.chapel.faith,58);assert.equal(resolved.blacksmith.equipped?.length,10);assert.equal(writeV2Save(checkedSnapshot(resolved)),writeV2Save(resolved));
});
