import {snapshotFixture} from '../gameInput.ts';
import type {GameSnapshot} from '../../src/save/saveGame.ts';
import assert from 'node:assert/strict';
import test from 'node:test';
import { createInitialState } from '../../src/engine/gameReducer.ts';
import { rawGameReducer as gameReducer } from '../gameInput.ts';
import {readV2Save,writeV2Save} from '../../src/save/saveGame.ts';
function market(v:unknown){assert.ok(typeof v==='object'&&v!==null&&'market' in v);const m=v.market;assert.ok(typeof m==='object'&&m!==null);return m;}
function roundtrip(v:unknown){const r=readV2Save(writeV2Save(v));assert.ok(r.ok);return r.state;}
function state(){const s=createInitialState(104);return {...s,phase:'management' as const,denarii:10000,marketPrices:{...s.marketPrices,sell:{...s.marketPrices.sell,wool:6}},season:'winter' as const,turn:4,synergies:{...s.synergies,activated:['market_king_1']},inventory:{...s.inventory,wool:0,iron:100,coal:100,wood:100}};}
test('Finite supply bounds profitable repeated wool purchases and survives Save/reload',()=>{let s: GameSnapshot=snapshotFixture(state());s=gameReducer(s,{type:'BLACKSMITH_FORGE_COMPLETE',payload:{itemId:'horseshoes',qualityScore:50,completionUid:1}});s=gameReducer(s,{type:'BLACKSMITH_EQUIP_ITEM',payload:{itemUid:1}});for(let i=0;i<100;i++){s=gameReducer(s,{type:'BUY_RESOURCE',payload:{resource:'wool',quantity:1,merchantId:'agnes'}});s=gameReducer(s,{type:'SELL_RESOURCE',payload:{resource:'wool',quantity:1,merchantId:'pieter'}});}const loaded=roundtrip(s);assert.equal(gameReducer(loaded,{type:'BUY_RESOURCE',payload:{resource:'wool',quantity:1,merchantId:'agnes'}}),loaded);assert.equal(loaded.inventory.wool,0);assert.ok('supply' in market(loaded));});
test('Posted, negotiated and Forge material purchases consume one shared resource supply',()=>{let s: GameSnapshot=snapshotFixture(state());s=gameReducer(s,{type:'BUY_RESOURCE',payload:{resource:'iron',quantity:95}});s=gameReducer(s,{type:'BLACKSMITH_BUY_RESOURCE',payload:{resource:'iron',quantity:5}});assert.equal(gameReducer(s,{type:'BUY_RESOURCE',payload:{resource:'iron',quantity:1}}),s);assert.equal(gameReducer(s,{type:'BLACKSMITH_BUY_RESOURCE',payload:{resource:'iron',quantity:1}}),s);assert.equal(gameReducer(s,{type:'HAGGLE_START',payload:{resource:'iron',quantity:1,merchantId:'wulfric',mode:'buy'}}),s);});
test('Outstanding buy bargain cannot bypass supply depleted after starting it',()=>{let s: GameSnapshot=snapshotFixture(state());s=gameReducer(s,{type:'HAGGLE_START',payload:{resource:'wool',quantity:5,merchantId:'agnes',mode:'buy'}});assert.ok('activeHaggle' in market(s));s=gameReducer(s,{type:'BUY_RESOURCE',payload:{resource:'wool',quantity:100,merchantId:'agnes'}});assert.equal(gameReducer(s,{type:'HAGGLE_ACCEPT'}),s);assert.notEqual(gameReducer(s,{type:'HAGGLE_WALK_AWAY'}),s);});
test('Old saves remain unchanged; malformed supply receipts reject instead of replenishing stock',()=>{const s=roundtrip(state());assert.ok(!('supply' in market(s)));for(const supply of [null,{turn:5,purchased:{}},{turn:4,purchased:{wool:101}},{turn:4,purchased:{wool:-1}},{turn:4,purchased:{wool:.5}},{turn:4,purchased:{alien:1}},{turn:0,purchased:{}}]){const raw=JSON.parse(writeV2Save(s));raw.state.market.supply=supply;assert.equal(readV2Save(JSON.stringify(raw)).ok,false);assert.throws(()=>writeV2Save({...s,market:{...market(s),supply}}));}});
import {MARKET_SUPPLY_PER_RESOURCE,remainingMarketSupply,isMarketSupply} from '../../src/engine/marketSupply.ts';
test('Only an actual calendar advance replenishes supply; simulation and Load do not',()=>{let s: GameSnapshot=snapshotFixture(state());s=gameReducer(s,{type:'BUY_RESOURCE',payload:{resource:'wool',quantity:100,merchantId:'agnes'}});assert.equal(remainingMarketSupply(market(s),4,'wool'),0);const simulated=gameReducer(s,{type:'SIMULATE_SEASON'});assert.equal(remainingMarketSupply(market(simulated),4,'wool'),0);const next=gameReducer({...s,phase:'random_resolve' as const},{type:'ADVANCE_TURN'});assert.equal(next.turn,5);assert.equal(remainingMarketSupply(market(roundtrip(next)),5,'wool'),MARKET_SUPPLY_PER_RESOURCE);assert.equal(isMarketSupply({turn:4,purchased:{}},5),false);});
test('Posted partial fills and negotiated purchases debit exactly, including buy-only goods',()=>{let s: GameSnapshot=snapshotFixture(state());s=gameReducer(s,{type:'BUY_RESOURCE',payload:{resource:'salt',quantity:98}});const before=s.denarii;const price=s.marketPrices.buy.salt;assert.ok(typeof price==='number');s=gameReducer(s,{type:'BUY_RESOURCE',payload:{resource:'salt',quantity:5}});assert.equal(s.denarii,before-2*price);assert.equal(roundtrip(s).inventory.salt,100);assert.equal(remainingMarketSupply(market(s),4,'salt'),0);s=gameReducer(s,{type:'HAGGLE_START',payload:{resource:'wool',quantity:5,merchantId:'agnes',mode:'buy'}});s=gameReducer(s,{type:'HAGGLE_ACCEPT'});assert.equal(remainingMarketSupply(market(roundtrip(s)),4,'wool'),95);assert.equal(s.inventory.wool,5);});
test('Malformed runtime receipts fail closed, and non-enumerable consumed receipts cannot be written',()=>{const s=state();for(const supply of [{turn:3,purchased:{}},{turn:4,purchased:{wool:NaN}},{turn:4,purchased:{wool:101}},Object.defineProperty({turn:4},'purchased',{value:{wool:100}})]){const bad={...s,market:{...s.market,supply}};assert.equal(gameReducer(bad,{type:'BUY_RESOURCE',payload:{resource:'wool',quantity:1,merchantId:'agnes'}}),bad);assert.throws(()=>writeV2Save(bad));}const nonenum={...s,market:Object.defineProperty({...s.market},'supply',{value:{turn:4,purchased:{wool:100}}})};assert.throws(()=>writeV2Save(nonenum));});
test('Purchased counts must be owned plain or null-prototype map entries to survive serialization',()=>{const s=state(),purchased=Object.create({wool:100}),bad={...s,market:{...s.market,supply:{turn:4,purchased}}};assert.equal(isMarketSupply(bad.market.supply,4),false);assert.equal(remainingMarketSupply(bad.market,4,'wool'),0);assert.throws(()=>writeV2Save(bad));const own=Object.assign(Object.create(null),{wool:100}),valid={...s,market:{...s.market,supply:{turn:4,purchased:own}}};assert.equal(isMarketSupply(valid.market.supply,4),true);assert.equal(remainingMarketSupply(market(roundtrip(valid)),4,'wool'),0);});
